### PR TITLE
Feature/placeholders

### PR DESCRIPTION
**Pull request by EugenMayer**
Implemented placeholders as we spoke about. Running it in production already, you can test it with `eugenmayer/concourse-ssh-resource`.

I also added integration tests to the projects, thats why overall the PR is a bit larger. This way we can test payloads and debug the actual behavior. i did not add all tests, but tested the placeholder feature.

we have 2 different ways to replace placholders, see the documentation addition ( `value` and `file` )

### CODE REVIEW

**Comment by EugenMayer** [comment]
I also fixed the Dockerfile to use the multi-builder pattern so our actual docker-image is smaller ( alpine only ) no golang compiler. I added a _test Dockerfile so we can run the integration tests included the tests - we could also mount the tests and use the production image in ( in the docker-compose ).

The integration tests actually really connect to the ssh server, see docker-compose-test.yml

**Comment by henry40408** [comment]
@EugenMayer close and reopen the PR to force CircleCI to rebuild

**Comment by henry40408** [comment]
@EugenMayer I would accept this PR, integrate your tests in CI, and draft a new release

Thanks a lot for your contribution 😄

**Comment by EugenMayer** [comment]
great news! Thank you and thank you for writing it in golang - the only reason why i considered contributing instead of writing my own. Well done!

**Pull request merged**
